export const HOME_DASHBOARD_ROUTE = '/'
export const CREATE_PASSWORD_ROUTE = '/create'
export const EDIT_PASSWORD_ROUTE = '/:passwordId/edit'
export const SETTINGS_ROUTE = '/settings'
export const NO_MATCH_ROUTE = '/no-match'
